### ISSUE TITLE
Removal of `default_app_config` on Django 3.2+

### ISSUE THREAD

**Issue by browniebroke** [adamchainz/django-upgrade#139]
### Description

Django 3.2 introduced an automatic [app config discovery mechanism](https://docs.djangoproject.com/en/dev/releases/3.2/#automatic-appconfig-discovery). Do you think django-upgrade could remove the deprecated `default_app_config` application configuration variable?

**Comment by adamchainz** [comment]
I guess so, I didn't think about it. I found this change affects installable apps more than projects, for which I used this pattern, rather than just deleting:

```python
import django

if django.VERSION < (3, 2):
    default_app_config = "django_linear_migrations.apps.DjangoLinearMigrationsAppConfig"
```

but yeah we could add a fixer, if a django-upgrade user specifies `--target-version 3.2`, that means their code should only support 3.2 as a minimum.

Are you offering to write a PR?

**Comment by browniebroke** [comment]
I can take a look at that, yes. I might have some free time later this week.
