### ISSUE TITLE
Use `@cached_property` for `State.looks_like_*` methods

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/django-upgrade#281]
### Description

Compute them once per `State`.

**Comment by UnknownPlatypus** [comment]
Funny, I was thinking about something similar too and did some profiling running `django-upgrade` on a 5363 python files repo. Here is a graph from cprofile for a noop operation (everything is already upgraded): 

<details>
 <summary><b>current.svg</b></summary>

<img src='https://user-images.githubusercontent.com/68703331/198829394-440bcfb1-a43b-42a3-9338-99629a39832b.svg'>
</details>

I noticed the `looks_like_dunder_init_file` in `default_app_config` was evaluated 10 times per files on average which felt a bit weird. **It's only 1% of the execution total though**.

One idea I had was to conditionally register fixer based on the expected django file type (admin file, setting file, etc), similarly to what is done with the django_version targeted by every fixer. An attempt to do that resulted in approximately **1-1.5% speed improvement**.

I just tried a similar benchmark using the cached_property approach and got some similar result with **~1% speed improvement**


<details>
 <summary><b>Empirical benchmark results</b></summary>

Round 1:
[current] -> best of 10: 4.563s
[cached_property] -> best of 10: 4.443s
[conditional_register] -> best of 10: 4.404s

Round 2:
[current] -> best of 10: 4.528s
[cached_property] -> best of 10: 4.492s
[conditional_register] -> best of 10: 4.404s

Round 3:
[current] -> best of 10: 4.557s
[cached_property] -> best of 10: 4.441s
[conditional_register] -> best of 10: 4.445s

</details>

And also, here are the profiling result for the `cached_property` and `conditional_register` approach. In both case, we can see the `looks_like_*` call disappear from the graph.


<details>
 <summary><b>cached_property.svg</b></summary>

<img src='https://user-images.githubusercontent.com/68703331/198829687-c5747f45-3d2b-41f5-9fbb-4e5c0340fa4e.svg'>
</details>


<details>
 <summary><b>conditional_register.svg</b></summary>

<img src='https://user-images.githubusercontent.com/68703331/198829688-3931eb67-c45a-4411-b02f-f1321466c2e1.svg'>
</details>

Anyway, we're a bit down a rabbit hole on this one :rabbit:. 
The speed improvements will likely be really small so the `cached_property` approach is probably the good one because it should be quite simple to add. We can also probably lift `looks_like_` check as much as possible in the different fixers to take advantage of that.

**Comment by adamchainz** [comment]
Thanks for the benchmarking! I haven't even tried yet. <9 seconds for 5363 files is very acceptable already 😎

Was this with [yelp-gprof2dot](https://pypi.org/project/yelp-gprof2dot/) ? 👀

> The speed improvements will likely be really small so the `cached_property` approach is probably the good one because it should be quite simple to add. We can also probably lift `looks_like_` check as much as possible in the different fixers to take advantage of that.

Conditional registration seems more complicated than it's worth. Would you like to make a PR using `cached_property` and hoisting the `looks_like_*` checks then?

**Comment by UnknownPlatypus** [comment]
> Thanks for the benchmarking! I haven't even tried yet. <9 seconds for 5363 files is very acceptable already :sunglasses:

ye honestly this is already fast for a whole repo upgrade :clap: 

> Was this with [yelp-gprof2dot](https://pypi.org/project/yelp-gprof2dot/) ? :eyes:

ye exactly, mostly using the same tooling as anthony (for exemple [in this video](https://www.youtube.com/watch?v=Q3menOSxRC4)). 
I've also tried [snakeviz](https://github.com/jiffyclub/snakeviz) in the past but I find it a bit less readable.

I'm down to work on a PR, I'm just wondering how to deal with the slotted class. `functools.cached_property` is [not compatible](https://docs.python.org/fr/3.8/library/functools.html#functools.cached_property) unless I add the `__dict__` name to the `__slots__` list.

**Comment by adamchainz** [comment]
> I'm down to work on a PR, I'm just wondering how to deal with the slotted class. `functools.cached_property` is [not compatible](https://docs.python.org/fr/3.8/library/functools.html#functools.cached_property) unless I add the `__dict__` name to the `__slots__` list.

Yeah thanks for that. `__slots__` is quite the micro-optimization, but worth keeping since we can.
