### ISSUE TITLE
Rewrite `queryset.filter(pk=obj.pk).exists()` to `queryset.contains(obj)`

### ISSUE THREAD

**Issue by jieter** [adamchainz/django-upgrade#362]
### Description

Rewrite `queryset.filter(pk=obj.pk).exists()` to `queryset.contains(obj)`. The latter tries `queryset._results_cache` first, which might save a query.

- Docs of [`QuerySet.contains`](https://docs.djangoproject.com/en/4.2/ref/models/querysets/#contains), 
- Implementation of [`QuerySet.contains`](https://github.com/django/django/blob/107865780aa44914e21d27fdf4ca269bc61c7f01/django/db/models/query.py#L1263-L1282)
- Added in Django 4.0

**Comment by UnknownPlatypus** [comment]
Should `if obj in some_queryset:` be rewritten to `if some_queryset.contains(obj):` to for the same reason?

**Comment by adamchainz** [comment]
I don't think we can safely perform this rewrite due to the first check in the implementation for `values()` and `values_list()`.

Say we have:

```python
qs = Book.objects.values_list("name")
...
if qs.filter(pk=obj.pk).exists():
    ...
```

... then we can't do the rewrite. But we also can't detect calls to `values()` / `values_list()` in most situations from the AST, since `QuerySets` can be constructed in all kinds of ways.

**Comment by jieter** [comment]
That's a pity, but you are probably right. My initial regexp-replace in our code base was also not very reliable.
