### ISSUE TITLE
HttpRequest.META is not deprecated

### ISSUE THREAD

**Issue by quentinelwin** [adamchainz/django-upgrade#72]
### Python Version

3.8.10

### Django Version

3.2

### Package Version

1.0.0

### Description

According to the [documentation of HttpRequest.META](https://docs.djangoproject.com/en/3.2/ref/request-response/#django.http.HttpRequest.META), HttpRequest.META is not deprecated in any version of django, so the rule in django-upgrade which converts these calls to `request.headers` and removes the HTTP prefix looks like it is too strict.

**Comment by adamchainz** [comment]
Django-upgrade doesn't just care about depreciations, it also helps you use the latest features.

**Comment by quentinelwin** [comment]
Sorry this is not what I understood about django-upgrade. I thought it only converted deprecated code to upgrade from one version of django to another, not that it was opinionated about some best practices (and in this particular case, it looks like this is not an official best practice, it is not mentionned in django documentation). Maybe you could write it more clearly in the description and documentation of the project?

**Comment by quentinelwin** [comment]
(My primary need here is to use a tool which makes the smaller amount of migrations in my codebase required to update the django version of my repo, at least as a first pass so that it is more digestable than a diff which would also add changes related to pretended best practices. These best practices changes could come as a second pass.)

**Comment by adamchainz** [comment]
I've improved the description in #73 to not only mention deprecations.

> (and in this particular case, it looks like this is not an official best practice, it is not mentionned in django documentation)

For old features we've been historically reticent to deprecate them or recommend the new one, because of the churn. My hope is this tool helps reduce the cost of that churn so we can make more required changes.

I don't think there's a reasonable claim that `request.META["HTTP_FOO"]` is "better" in any way to `request.headers["Foo"]`. The old way is just terrible and unfriendly.

> (My primary need here is to use a tool which makes the smaller amount of migrations in my codebase required to update the django version of my repo, at least as a first pass so that it is more digestable than a diff which would also add changes related to pretended best practices. These best practices changes could come as a second pass.)

I have sympathy for this approach but I don't really want to complicate django-upgrade. [pyupgrade](https://github.com/asottile/pyupgrade) takes a similar "all or nothing" approach, albeit with three special case flags.

I would add a flag if there was a potential bug or compelling reason to keep `request.META`, but I don't see one. If you want to incrementally add the changes, you can always use `git add --patch` for your commit or [filter hunks with a regex](https://stackoverflow.com/questions/13192594/add-patch-in-git-all-hunks-matching-regex-in-file).

**Comment by quentinelwin** [comment]
> I've improved the description in #73 to not only mention deprecations.

OK thanks :)
